# Generated by Django 5.2.5 on 2025-08-25 20:28

import api.model.Member
import api.model.Track
import api.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='personal_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.model.Member.member_image, validators=[api.validators.validate_image_mime], verbose_name='Member Image'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Track ID')),
                ('name', models.CharField(max_length=255, validators=[api.validators.validate_name], verbose_name='Track Name')),
                ('bio', models.TextField(blank=True, null=True, validators=[api.validators.validate_safe_text], verbose_name='Track Bio')),
                ('duration', models.DurationField(verbose_name='Track Duration')),
                ('cover', models.ImageField(default='track_covers/audio_template.jpg', upload_to='track_covers/')),
                ('audio_file', models.FileField(upload_to=api.model.Track.track_audio, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac', 'ogg', 'aac', 'm4a']), api.validators.validate_audio_mime])),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
