# Generated by Django 5.2.5 on 2025-08-25 21:29

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_member_personal_img_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(default='track_covers/audio_template.jpg', upload_to='track_covers/', validators=[api.validators.validate_image_mime]),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Track Duration'),
        ),
    ]
