# Generated by Django 5.2.5 on 2025-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_track_cover_alter_track_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(default=0, verbose_name='Track Duration'),
            preserve_default=False,
        ),
    ]
