# Generated by Django 5.2.5 on 2025-08-26 14:08

import api.model.Playlist
import api.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_track_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[api.validators.validate_name])),
                ('cover', models.ImageField(blank=True, null=True, upload_to=api.model.Playlist.playlist_cover, validators=[api.validators.validate_image_mime])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tracks', models.ManyToManyField(blank=True, to='api.track')),
            ],
        ),
    ]
