# Generated by Django 5.2.5 on 2025-10-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment_follow_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('HipHop', 'HipHop'), ('Electronic', 'Electronic'), ('Country', 'Country'), ('Reggae', 'Reggae'), ('Blues', 'Blues'), ('Metal', 'Metal'), ('Folk', 'Folk'), ('RnB', 'RnB'), ('Arabic', 'Arabic'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Track Genre'),
        ),
    ]
