# Generated by Django 5.2.5 on 2025-10-21 17:58

import api.model.Track
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_track_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='plays',
            field=models.BigIntegerField(default=0, verbose_name='Number of Plays'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to=api.model.Track.track_audio, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac', 'ogg', 'aac', 'm4a'])]),
        ),
    ]
