# Generated by Django 5.2.5 on 2026-03-23 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stream',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='api.track'),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('member', 'track')},
        ),
    ]
