# Generated by Django 5.2.5 on 2026-03-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_stream_member_alter_stream_track_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='isCounted',
            new_name='is_counted',
        ),
        migrations.AddField(
            model_name='stream',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
