# Generated by Django 5.2.5 on 2026-03-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_iscounted_stream_is_counted_stream_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='is_counted',
        ),
        migrations.AddField(
            model_name='stream',
            name='time_spent',
            field=models.BigIntegerField(default=0, verbose_name='time spent in seconds'),
        ),
    ]
