# Generated by Django 5.2.5 on 2026-03-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_stream_is_active_remove_stream_is_counted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stream',
            name='is_counted',
            field=models.BooleanField(default=False),
        ),
    ]
