# Generated by Django 5.2.5 on 2026-04-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_stream_is_active_stream_is_counted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Track Duration'),
        ),
    ]
