# Generated by Django 5.2.5 on 2026-04-30 11:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_track_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='plays',
        ),
        migrations.AddField(
            model_name='track',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 30, 11, 28, 54, 583043, tzinfo=datetime.timezone.utc), verbose_name='Published At'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='api.track')),
            ],
        ),
    ]
