# Generated by Django 5.2.5 on 2026-05-04 20:58

import api.model.Member
import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_comment_created_at_alter_play_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='wallpaper_img',
            field=models.ImageField(blank=True, null=True, upload_to=api.model.Member.member_wallpaper, validators=[api.validators.validate_image_mime], verbose_name='Member Wallpaper'),
        ),
    ]
