# Generated by Django 5.2.5 on 2026-05-04 20:59

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_member_wallpaper_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, null=True, validators=[api.validators.validate_safe_text], verbose_name='Member Bio'),
        ),
    ]
