# Generated by Django 5.2.5 on 2026-05-07 12:56

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_member_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(db_index=True, max_length=50, validators=[api.validators.validate_name], verbose_name='Member Name'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('HipHop', 'HipHop'), ('Electronic', 'Electronic'), ('Country', 'Country'), ('Reggae', 'Reggae'), ('Blues', 'Blues'), ('Metal', 'Metal'), ('Folk', 'Folk'), ('RnB', 'RnB'), ('Arabic', 'Arabic'), ('Other', 'Other')], db_index=True, default='Other', max_length=50, verbose_name='Track Genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(db_index=True, max_length=255, validators=[api.validators.validate_name], verbose_name='Track Name'),
        ),
    ]
